---
packages:
  - apache2
  - curl
  - acl
  - ufw

kijani_group: kijanikiosk

users:
  - kk-api
  - kk-payments
  - kk-logs

directories:
  - /opt/kijanikiosk/config
  - /opt/kijanikiosk/shared/logs
  - /opt/kijanikiosk/health
