apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-payments
  namespace: kijani-staging
  annotations:
    kubernetes.io/change-cause: "Capstone staging deployment"
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kk-payments
  template:
    metadata:
      labels:
        app: kk-payments
    spec:
      containers:
        - name: kk-payments
          image: host.minikube.internal:8082/kk-payments:9.9.9-broken
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: PORT
              value: "3001"
            - name: APP_VERSION
              value: "v1.3.0-staging"
          envFrom:
            - configMapRef:
                name: kk-payments-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
